modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="mechwildmechs"
version="0.7.0"
displayName="Mechwild Mechs"
description="First true custom beast-mech prototype for Mechwild Ascension. Adds a cockpit-entry beast-mech entity, repair interaction, frame movement tuning and active abilities."
[[dependencies.mechwildmechs]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.mechwildmechs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
