modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="mechwildmechs"
version="0.8.0"
displayName="Mechwild Mechs"
description="v0.8 visual cockpit pass. Adds a larger red/black raptor mech shell, higher cockpit camera feel, pilot hand hiding, and green first-person cockpit HUD overlay."
[[dependencies.mechwildmechs]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.mechwildmechs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
